name: Build and test pull request
"on": pull_request_target
jobs:
  build_and_test:
    permissions: write-all
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checking out PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Creating env file
        run: |
          touch .env
          echo REACT_APP_SITE_KEY=${{ secrets.REACT_APP_SITE_KEY }} >> .env
          echo REACT_APP_DEBUG_KEY=${{ secrets.REACT_APP_DEBUG_KEY }} >> .env
          echo REACT_APP_FIREBASE_ENV=TEST >> .env
          cat .env

      - name: Building application
        run: npm ci && npm run build

      - name: Running Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start

      - name: Scanning dependencies for EOL
        uses: xeol-io/xeol-action@v1.1.0
        with:
          path: "."

      - name: Deploying to firebase PREVIEW
        if: github.actor != 'dependabot[bot]'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_LEADER_BOARD_APP_TEST }}"
          projectId: leader-board-app-test
